In [52]:
from word2number import w2n
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
import numpy as np
import math

In [73]:
data=pd.read_csv("hiring.csv")
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

# data preprocessing

In [74]:
data.experience.fillna("zero",inplace=True)

In [75]:
def ans(x):
    try:
        return w2n.word_to_num(x)
    except:
        return np.nan
data["experience"] = data["experience"].apply(ans)

In [76]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [79]:
median_test_score = math.floor(data["test_score(out of 10)"].mean())
median_test_score

7

In [80]:
data["test_score(out of 10)"].fillna(math.floor(median_test_score),inplace=True)

In [81]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [82]:
lm=linear_model.LinearRegression()
z=data[["experience","test_score(out of 10)","interview_score(out of 10)"]]
lm.fit(z,data[["salary($)"]])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [83]:
lm.intercept_

array([14992.65144669])

In [84]:
lm.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [85]:
lm.predict([[2,9,6]])

array([[53713.86677124]])

In [86]:
lm.predict([[12,10,10]])

array([[93747.79628651]])